# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        #AppBundle\Entity\User: plaintext
        Symfony\Component\Security\Core\User\User: plaintext
            
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        symfony_dev:
            entity: 
                class: AppBundle:User
                property: username
        in_memory:
            memory:
                users:
                    faza:
                        password: faza1234
                        #password: 7a410767268fb25be71a79fc7634bf18
                        roles: 'ROLE_USER'
                    admin:
                        password: admin1234
                        roles: 'ROLE_ADMIN'
                        
    firewalls:
        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
            
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
